{{- if  .Values.podMonitoring.enabled }}
apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  labels:
    {{- include "cloudflare-exporter.labels" . | nindent 4 }}
  {{- if .Values.podMonitoring.labels }}
    {{- toYaml .Values.podMonitoring.labels | nindent 4 }}
  {{- end }}
  name: {{ template "cloudflare-exporter.fullname" . }}
{{- if .Values.podMonitoring.namespace }}
  namespace: {{ .Values.podMonitoring.namespace }}
{{- end }}
spec:
  endpoints:
  - port: http
{{- if .Values.podMonitoring.interval }}
    interval: {{ .Values.podMonitoring.interval }}
{{- end }}
{{- if .Values.podMonitoring.telemetryPath }}
    path: {{ .Values.podMonitoring.telemetryPath }}
{{- end }}
{{- if .Values.podMonitoring.metricRelabelings }}
    metricRelabelings:
{{ toYaml .Values.podMonitoring.metricRelabelings | indent 4 }}
{{- end }}
{{- if .Values.podMonitoring.relabelings }}
    relabelings:
{{ toYaml .Values.podMonitoring.relabelings | indent 4 }}
{{- end }}
  selector:
    matchLabels:
      {{- include "cloudflare-exporter.selectorLabels" . | nindent 6 }}
{{- if .Values.podMonitoring.targetLabels }}
  targetLabels:
{{- range .Values.podMonitoring.targetLabels }}
    - {{ . }}
{{- end }}
{{- end }}
{{- end }}
